#index:
#    path: /
#    controller: App\Controller\DefaultController::index

parser:
    resource: '@ParserBundle/Infrastructure/Resources/config/routes.yaml'

remote_user:
    resource: '@RemoteUserBundle/Infrastructure/Resources/config/routes.yaml'
    prefix: /remote_user