services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\ParserBundle\:
    resource: '../../../../ParserBundle'
    exclude:
      - './ParserBundle/DependencyInjection/'
      - './ParserBundle/Entity/'
      - './ParserBundle/Kernel.php'

  App\ParserBundle\Presentation\: # assuming you have namespace like that
    resource: '../../../Presentation/*/Controller'
    tags: [ 'controller.service_arguments' ]

  App\ParserBundle\Infrastructure\FileReader\ExtensionAwareFileReader:
    calls:
      - addReader: [ '@App\ParserBundle\Infrastructure\FileReader\ZipFileReader' ],
      - addReader: [ '@App\ParserBundle\Infrastructure\FileReader\JsonFileReader' ]

  App\ParserBundle\Infrastructure\FileReader\FileReaderInterface: '@App\ParserBundle\Infrastructure\FileReader\ExtensionAwareFileReader'

  App\ParserBundle\Infrastructure\Shared\Filesystem\LocalFilesystem:
    - '%kernel.project_dir%/upload/'


  App\ParserBundle\Application\AuthenticateShoprenterWorker\AuthenticateShoprenterWorkerHandler:
    tags:
      - name: messenger.message_handler
        bus: query.bus
        handles: App\ParserBundle\Application\AuthenticateShoprenterWorker\AuthenticateShoprenterWorkerQuery

  App\ParserBundle\Application\GetImages\GetImagesHandler:
    tags:
      - name: messenger.message_handler
        bus: query.bus
        handles: App\ParserBundle\Application\GetImages\GetImagesQuery

  App\ParserBundle\Application\GetShoprenterWorkerById\GetShoprenterWorkerByIdHandler:
    tags:
      - name: messenger.message_handler
        bus: query.bus
        handles: App\ParserBundle\Application\GetShoprenterWorkerById\GetShoprenterWorkerByIdQuery
